export enum AppRoutes {
  Home = "/",
  Login = "/login",
  Dashboard = "/dashboard",
  Admin = "/admin",
  Plans = "plans",
  Campaigns = "campaigns",
  Bespoke = "bespoke",
  Practices = "practices",
  PeopleAccess = "people-and-access",
  AuditLogs = "audit-logs",
  Settings = "settings",
  Help = "help-and-support",
  Notifications = "notifications",
  GodMode = "god-mode",
  SendEmail = "send-email",
  EmailHealth = "email-health",
  PracticesOfInterest = "practices-of-interest",
  BugReports = "bug-reports",
  FAQs = "/faqs",
  NotificationsCenter = "/notifications-center",
  Landing = "/landing",
}

export enum DatabaseTables {
  Users = "users",
  Campaigns = "campaigns",
  CampaignsCatalog = "campaigns_catalog",
  Selections = "selections",
  Practices = "practices",
  Allowed_Users = "allowed_users",
  BespokeCampaigns = "bespoke_campaigns",
  Notifications = "notifications",
  CommunicationLogs = "selection_status_history",
  PracticeMembers = "practice_members",
}

export enum RPCFunctions {
  LinkUser = "link_current_user",
  AssignUserToPractice = "assign_user_to_practice",
  UnAssignUserFromPractice = "unassign_user_from_practice",
  GetCampaigns = "get_campaigns",
  CreateBespokeSelection = "create_bespoke_selection",
  CreateBespokeEvent = "create_bespoke_event",
  AddCampaignsBulk = "add_campaigns_bulk",
  GetGuidedCampaigns = "get_guided_campaigns",
  GetPlans = "get_plans",
  GetUsers = "get_users",
  UpdateUser = "update_user",
  BulkUploadUsers = "bulk_upsert_allowed_users_with_practices",
  GetFilterOptions = "get_filter_options",
  CopyPracticeCampaigns = "copy_practice_campaigns",
  GetAssets = "get_assets",
  RequestAssets = "request_assets",
  RequestAssetsBulk = "request_assets_bulk",
  ListNotifications = "list_notifications",
  SubmitAssets = "submit_assets",
  MarkAsRead = "mark_notification_read",
  DeleteSelection = "delete_selection",
  QueuePracticeOnboardingEmail = "queue_practice_onboarding_email",
  ConfirmAssets = "confirm_assets",
  RequestRevision = "request_revision",
  GodModeSearchSelections = "god_mode_search_selections",
  GodModeGetSelectionDetails = "god_mode_get_selection_details",
  GodModeUpdateSelection = "god_mode_update_selection",
  GodModeUpdateBespokeCampaign = "god_mode_update_bespoke_campaign",
  GodModeForceStatus = "god_mode_force_status",
  GodModeUpdateNotificationPayloads = "god_mode_update_notification_payloads",
  GodModeRecreateNotification = "god_mode_recreate_notification",
  GodModeForceMarkRead = "god_mode_force_mark_read",
  GodModeLogResend = "god_mode_log_resend",
  GodModeDeleteSelection = "god_mode_delete_selection",
  GodModeArchiveSelection = "god_mode_archive_selection",
  GodModeReassignPractice = "god_mode_reassign_practice",
  GodModeListPractices = "god_mode_list_practices",
  GodModeReplaceNotificationPayload = "god_mode_replace_notification_payload",
  GodModeUpdateSelectionCreatives = "god_mode_update_selection_creatives",
  AddCampaignWithAssets = "add_campaign_with_assets",
  CreateBespokeSelectionV2 = "create_bespoke_selection_v2",
  CreateBespokeEventV2 = "create_bespoke_event_v2",
  CopyPracticeCampaignsV2 = "copy_practice_campaigns_v2",
  SubmitDraftSelection = "submit_draft_selection",
  LogEmailAttempt = "log_email_attempt",
  FinaliseEmailAttempt = "finalise_email_attempt",
  ListPracticesOfInterest = "list_practices_of_interest",
  AddPracticeOfInterest = "add_practice_of_interest",
  RemovePracticeOfInterest = "remove_practice_of_interest",
  AddSelectionComment = "add_selection_comment",
  EditSelectionComment = "edit_selection_comment",
  DeleteSelectionComment = "delete_selection_comment",
  ListSelectionComments = "list_selection_comments",
  ListMyCommentInbox = "list_my_comment_inbox",
  MarkCommentRead = "mark_comment_read",
  MarkAllCommentsRead = "mark_all_comments_read",
  UnreadCommentCount = "unread_comment_count",
  RecordMarkupOpened = "record_markup_opened",
  CreateBugReport = "create_bug_report",
  ListBugReports = "list_bug_reports",
  CloseBugReport = "close_bug_report",
  ReopenBugReport = "reopen_bug_report",
  DeleteBugReport = "delete_bug_report",
}

export enum UserRoles {
  User = "user",
  Admin = "admin",
  SuperAdmin = "super_admin",
}

export enum SelectionStatus {
  Draft = "draft",
  OnPlan = "onPlan",
  Requested = "requested",
  InProgress = "inProgress",
  AwaitingApproval = "awaitingApproval",
  Confirmed = "confirmed",
  Live = "live",
  Completed = "completed",
}

// Actor notification types (for in-app notifications when user performs CRUD actions)
export enum ActorNotificationType {
  CampaignAdded = "campaignAdded",
  CampaignUpdated = "campaignUpdated",
  CampaignDeleted = "campaignDeleted",
  BespokeAdded = "bespokeAdded",
  BespokeEventAdded = "bespokeEventAdded",
  BulkAdded = "bulkAdded",
  CampaignsCopied = "campaignsCopied",
}

export enum SelectionsSource {
  Manual = "manual",
  Quick = "quick",
  Guided = "guided",
  Admin = "admin",
}

export enum SelectionTier {
  Good = "good",
  Better = "better",
  Best = "best",
}

export enum SelectionActivity {
  Event = "Event",
  BrandActivations = "brand activation",
  Campaign = "campaign",
  Evergreen = "evergreen",
}
